version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./backend
    restart: always
    ports:
      - '5001:5001'
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    restart: always
    ports:
      - '80:80'
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
volumes:
  mongo-data: 