version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./backend
    restart: always
    expose:
      - '5001'
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    restart: always
    expose:
      - '80'
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  caddy:
    image: caddy:2
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
volumes:
  mongo-data: 
  caddy-data:
  caddy-config: