name: CD Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start SSH‑agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Write .env on the server
        env:
          BACKEND_ENV: "${{ secrets.BACKEND_ENV }}"
          FRONTEND_ENV: "${{ secrets.FRONTEND_ENV }}"
        run: |
          ssh -o StrictHostKeyChecking=yes \
              ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          mkdir -p ~/app/backend ~/app/frontend
            echo "${BACKEND_ENV}" > ~/app/backend/.env
            echo "${FRONTEND_ENV}" > ~/app/frontend/.env
          EOF

      - name: Deploy on VPS
        run: |
          ssh -o StrictHostKeyChecking=yes \
              ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          cd /home/${{ secrets.VPS_USER }}/app
          git fetch --all
          git reset --hard origin/main
          docker-compose pull
          docker-compose up -d --build
          EOF
