name: CD Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start SSH-agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Write .env on the server
        env:
          BACKEND_ENV: ${{ secrets.BACKEND_ENV }}
          FRONTEND_ENV: ${{ secrets.FRONTEND_ENV }}
        run: |
          ssh -o StrictHostKeyChecking=yes ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            mkdir -p ~/app/backend ~/app/frontend
            echo \"$BACKEND_ENV\" > ~/app/backend/.env
            echo \"$FRONTEND_ENV\" > ~/app/frontend/.env
          "

      - name: Deploy on VPS
        run: |
          ssh -o StrictHostKeyChecking=yes ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            cd ~/app
            docker compose down
            git fetch --all
            git reset --hard origin/main
            docker compose pull
            docker compose up -d --build
          "
